---
- name: Create Backup Agent volume
  docker_volume:
    name: "h42backup_agent_config"
    state: present

- name: Create backup container
  docker_container:
    name: "h42.backup-agent"
    state: present
    restart_policy: unless-stopped
    image: "h42-backup/agent"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "h42backup_agent_config:/h42backup/config"
    env:
      TZ: "{{ timezone }}"
      H42BACKUP_HOSTNAME: "{{ inventory_hostname }}"
      H42BACKUP_REPO: "{{ backup.borg.repo }}"
      H42BACKUP_PASSPHRASE: "{{ backup.borg.passphrase }}"
    labels:
      one.h42.backup.enable: "false"

- name: Start backup container
  docker_container:
    name: "h42.backup-agent"
    state: started
