---
jellyfin_version: 10.8.13-1
jellyfin_hw_packages:
  - vainfo

plex_version: 1.40.2.8395-c67dce28e
plex_hw_packages:
  - vainfo

squid_version: 5.2-22.04_edge
pyload_version: 0.5.0

jdownloader_version: v23.11.1