---
- name: "Install proxy"
  include: "{{ hostvars[inventory_hostname].features[fitem].proxy.vendor }}-proxy.yml"
  loop: "{{ features.keys() | list }}"
  loop_control:
    loop_var: "fitem"
  when: 
    - hostvars[inventory_hostname].features[fitem].proxy is defined
    - hostvars[inventory_hostname].features[fitem].proxy.vendor is defined
