---
- name: "Generate Dovecot Configuration"
  include: "dovecot-configuration.yml"

- name: "Dovecot Firewall Configuration"
  include: "dovecot-firewall.yml"

- name: Create vmail data volume
  docker_volume:
    name: "{{ features.mail.name | default('mail') | lower }}_vmail_data"
    state: present

- name: Create letsencrypt data volume
  docker_volume:
    name: "{{ features.mail.name | default('mail') | lower }}_dovecot_letsencrypt"
    state: present

- name: "Create Dovecot container"
  docker_container:
    name: "{{ features.mail.name | default('mail') | lower }}.dovecot"
    state: present
    restart_policy: unless-stopped
    image: "dockmail/dovecot"
    volumes:
      - "{{ features.mail.name | default('mail') | lower }}_vmail_data:/var/mail"
      - "{{ features.mail.name | default('mail') | lower }}_dovecot_letsencrypt:/etc/letsencrypt"
      - "/opt/cloud/{{ features.mail.name | default('mail') | lower }}/dovecot:/etc/dovecot/"
    env:
      TZ: "{{ timezone }}"
      HOSTNAME: "{{ features.mail.postfix.hostname }}"
    labels:
      one.h42.nhfw.enable: "true"
      one.h42.nhfw.dns.register: "true"
      docker.network: "{{ features.mail.network }}"
    networks_cli_compatible: yes
    networks:
      - name: "{{ features.mail.network }}"
        ipv6_address: "{{ features.mail.dovecot.ipv6 }}"
        ipv4_address: "{{ features.mail.dovecot.ipv4 | default(None) }}"
        links:
          - "{{ features.mail.name | default('mail') | lower }}.{{ features.mail.database.vendor }}"
          - "{{ features.mail.name | default('mail') | lower }}.postfix"
  when:
    - features.mail.database is defined

- name: "Start Dovecot container"
  docker_container:
    name: "{{ features.mail.name | default('mail') | lower }}.dovecot"
    state: started
