---
- name: "Create Roundcube container"
  docker_container:
    name: "{{ features.mail.name | default('mail') | lower }}.roundcube"
    state: present
    restart_policy: unless-stopped
    image: "roundcube/roundcubemail:{{ roundcube_version }}"
    env:
      TZ: "{{ timezone }}"
      ROUNDCUBEMAIL_DB_TYPE: "mysql"
      ROUNDCUBEMAIL_DB_HOST: "{{ features.mail.name | default('mail') | lower }}.{{ features.mail.database.vendor }}"
      ROUNDCUBEMAIL_DB_USER: "roundcube"
      ROUNDCUBEMAIL_DB_PASSWORD: "{{ features.mail.database.otherusers.roundcube.password }}"
      ROUNDCUBEMAIL_DB_NAME: "roundcube"
      ROUNDCUBEMAIL_DEFAULT_HOST: "ssl://{{ features.mail.dovecot.hostname }}"
      ROUNDCUBEMAIL_DEFAULT_PORT: "993"
      ROUNDCUBEMAIL_SMTP_SERVER: "ssl://{{ features.mail.postfix.hostname }}"
      ROUNDCUBEMAIL_SMTP_PORT: "465"
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: "20M"
    labels:
      one.h42.nhfw.enable: "true"
      one.h42.nhfw.dns.register: "true"
      docker.network: "{{ features.mail.network }}"
      traefik.enable: "true"
      traefik.http.routers.roundcube.rule: "Host(`{{ features.mail.roundcube.hostname }}`)"
      traefik.http.routers.roundcube.entrypoints: "web"
      traefik.http.routers.roundcube.middlewares: "httpsredirect@file"
      traefik.http.routers.roundcube-ssl.rule: "Host(`{{ features.mail.roundcube.hostname }}`)"
      traefik.http.routers.roundcube-ssl.entrypoints: "websecure"
      traefik.http.routers.roundcube-ssl.middlewares: "hsts@file,httpsredirect@file"
      traefik.http.routers.roundcube-ssl.tls.certresolver: "letsencrypt"
      traefik.http.routers.roundcube-ssl.tls.options: "intermediate@file"
      traefik.http.services.roundcube-ssl.loadbalancer.server.port: "80"
    networks_cli_compatible: yes
    networks:
      - name: "{{ features.mail.network }}"
        ipv6_address: "{{ features.mail.roundcube.ipv6 }}"
        ipv4_address: "{{ features.mail.roundcube.ipv4 | default(None) }}"
        links:
          - "{{ features.mail.name | default('mail') | lower }}.{{ features.mail.database.vendor }}"
  when:
    - features.mail.database is defined
    - features.mail.postfix is defined
    - features.mail.dovecot is defined

- name: "Start Roundcube container"
  docker_container:
    name: "{{ features.mail.name | default('mail') | lower }}.roundcube"
    state: started
