---
- name: "Firewall Collabora outbound"
  ufw:
    rule: allow
    route: yes
    src: "{{ features.nextcloud.collabora.ipv6 }}"
    dest: "::/0"
    proto: "tcp"
    port: "{{ item }}"
  loop: 
    - "80"
    - "443"