---
- name: "Firewall OnlyOffice outbound"
  ufw:
    rule: allow
    route: yes
    src: "{{ features.nextcloud.onlyoffice.ipv6 }}"
    dest: "::/0"
    proto: "tcp"
    port: "{{ item }}"
  loop: 
    - "80"
    - "443"