---
- name: Firewall docker0 dns
  ufw:
    rule: allow
    route: yes
    src: "{{ docker.network.docker0.ipv6 }}"
    dest: "{{ item.0 }}"
    proto: "{{ item.1 }}"
    port: "53"
  with_nested:
    - "{{ docker.network.dns }}"
    - ["tcp", "udp"]

- name: Firewall other bridge
  ufw:
    rule: allow
    route: yes
    src: "{{ item.2.ipv6  }}"
    dest: "{{ item.0 }}"
    proto: "{{ item.1 }}"
    port: "53"
  with_nested: 
    - "{{ docker.network.dns }}"
    - ["tcp", "udp"]
    - "{{ docker.network.bridge }}"
  when: "docker.network.bridge is defined"

- name: Firewall allow inter container communication
  shell: "ufw route allow in on {{ item.br }} out on {{ item.br }}"
  loop: "{{ docker.network.bridge }}"
  when: "docker.network.bridge is defined"
