---
# Specific distribution
- name: "{{ ansible_distribution }} Docker setup"
  include: "setup-{{ ansible_distribution | lower }}.yml"
  when: docker is defined

- name: "Docker network setup"
  include: "network.yml"
  when: docker is defined

- name: "Docker NFS volume setup"
  include: "volume-nfs.yml"
  when: 
    - docker is defined
    - docker.volume_nfs is defined


- name: "Docker volume setup"
  include: "volume.yml"
  when: 
    - docker is defined
    - docker.volume is defined

- name: "Firewall setup for Docker"
  include: "firewall-home.yml"
  when: 
    - docker is defined
    - side == "home"
  
- name: "Firewall setup for Docker"
  include: "firewall-cloud.yml"
  when: 
    - docker is defined
    - side == "cloud"
  