---
- name: "Install database"
  include: "database.yml"
  loop: "{{ features.keys() | list }}"
  loop_control:
    loop_var: "fitem"
  when: 
    - hostvars[inventory_hostname].features[fitem].database is defined
