---
- name: "Test database existing"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.mariadb mysql --user=root --password={{ current_item.database.root_password }} --execute=\"USE {{ dbuser }};\""
  register: database_stat
  failed_when: no
  changed_when: no

## not database_stat.rc == 0 -> when the database not exists : the "USE {{ dbuser }};" return a exit code 1 -> database not exists.

- name: "Create database"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.mariadb mysql --user=root --password={{ current_item.database.root_password }} --execute=\"CREATE DATABASE IF NOT EXISTS {{ dbuser }};\""
  when:
    - not database_stat.rc == 0

- name: "Create user"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.mariadb mysql --user=root --password={{ current_item.database.root_password }} --execute=\"GRANT ALL PRIVILEGES ON {{ dbuser }}.* TO '{{ dbuser }}'@'%' IDENTIFIED BY '{{ current_item.database.otherusers[dbuser].password }}';\""
  when:
    - not database_stat.rc == 0

- name: "Flush privileges"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.mariadb mysql --user=root --password={{ current_item.database.root_password }} --execute=\"FLUSH PRIVILEGES;\""
  when:
    - not database_stat.rc == 0
