---
- name: "Test database existing"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.mariadb mysql --user=root --password={{ current_item.database.mariadb.root_password }} --execute=\"USE {{ dbname }};\""
  register: database_stat
  failed_when: no
  changed_when: no

## not database_stat.rc == 0 -> when the database not exists : the "USE {{ dbname }};" return a exit code 1 -> database not exists.

- name: "Create database"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.mariadb mysql --user=root --password={{ current_item.database.mariadb.root_password }} --execute=\"CREATE DATABASE IF NOT EXISTS {{ dbname }};\""
  when:
    - not database_stat.rc == 0

- name: "Create user"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.mariadb mysql --user=root --password={{ current_item.database.mariadb.root_password }} --execute=\"GRANT ALL PRIVILEGES ON {{ dbname }}.* TO '{{ current_item.database.mariadb.databases[dbname].username }}'@'%' IDENTIFIED BY '{{ current_item.database.mariadb.databases[dbname].password }}';\""
  when:
    - not database_stat.rc == 0

- name: "Flush privileges"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.mariadb mysql --user=root --password={{ current_item.database.mariadb.root_password }} --execute=\"FLUSH PRIVILEGES;\""
  when:
    - not database_stat.rc == 0
