---
- name: "Define current scope values"
  set_fact: 
    current_item: "{{ hostvars[inventory_hostname].features[fitem] }}"

- name: "Feature item values"
  debug: 
    var: current_item

- name: "Create mariadb data volume"
  docker_volume:
    name: "{{ current_item.name | default(fitem) | lower }}_mariadb_data"
    state: present

- name: "Create mariadb container"
  docker_container:
    name: "{{ current_item.name | default(fitem) | lower }}.mariadb"
    state: present
    restart_policy: unless-stopped
    image: "mariadb:{{ mariadb_version }}"
    volumes:
      - "{{ current_item.name | default(fitem) | lower }}_mariadb_data:/var/lib/mysql"
    env:
      TZ: "{{ timezone }}"
      MYSQL_ROOT_PASSWORD: "{{ current_item.database.mariadb.root_password }}"
    labels:
      one.h42.nhfw.enable: "true"
      one.h42.nhfw.dns.register: "true"
      docker.network: "{{ current_item.network }}"
    networks_cli_compatible: yes
    networks:
      - name: "{{ current_item.network }}"
        ipv6_address: "{{ current_item.database.mariadb.ipv6 }}"

- name: "Start mariadb container"
  docker_container:
    name: "{{ current_item.name | default(fitem) | lower }}.mariadb"
    state: started

- name: "Configure mariadb admin"
  include: mariadb-phpmyadmin.yml
  when: current_item.database.mariadb.admin is defined

- name: "Create Database and User"
  include: mariadb-database.yml
  loop: "{{ current_item.database.mariadb.databases.keys() | list }}"
  loop_control:
    loop_var: "dbname"
  when: current_item.database.mariadb.databases is defined
