---
- name: "Define current scope values"
  set_fact: 
    current_item: "{{ hostvars[inventory_hostname].features[fitem] }}"

- name: "Feature item values"
  debug: 
    var: current_item

- name: Create mariadb data volume
  docker_volume:
    name: "{{ current_item.name | default(fitem) | lower }}_mariadb_data"
    state: present

- name: Create mariadb container
  docker_container:
    name: "{{ current_item.name | default(fitem) | lower }}.mariadb"
    state: present
    restart_policy: unless-stopped
    image: "mariadb:{{ mariadb_version }}"
    volumes:
      - "{{ current_item.name | default(fitem) | lower }}_mariadb_data:/var/lib/mysql"
    env:
      TZ: "{{ timezone }}"
      MYSQL_ROOT_PASSWORD: "{{ current_item.database.root_password }}"
      MYSQL_DATABASE: "{{ current_item.name | default(fitem) | lower }}"
      MYSQL_USER: "{{ current_item.name | default(fitem) | lower }}"
      MYSQL_PASSWORD: "{{ current_item.database.user_password }}"
    labels:
      one.h42.nhfw.enable: "true"
      one.h42.nhfw.dns.register: "true"
    networks_cli_compatible: yes
    networks:
      - name: "{{ current_item.network }}"

- name: Start mariadb container
  docker_container:
    name: "{{ current_item.name | default(fitem) | lower }}.mariadb"
    state: started

- include: mariadb-phpmyadmin.yml
  when: current_item.database.admin_hostname is defined

- include: mariadb-user.yml
  loop: "{{ current_item.database.otherusers.keys() | list }}"
  loop_control:
    loop_var: "dbuser"
  when: current_item.database.otherusers is defined
