---
- name: Create nginx container
  docker_container:
    name: "web.{{ current_item.name | lower }}"
    state: present
    restart_policy: unless-stopped
    image: "nginx:{{ nginx_version }}"
    env:
      TZ: "{{ timezone }}"
    labels:
      one.h42.nhfw.enable: "true"
      one.h42.nhfw.dns.register: "true"
      docker.network: "{{ current_item.network }}"
      traefik.enable: "true"
      traefik.http.routers.web.rule: "Host(`{{ current_item.web.hostname }}`)"
      traefik.http.routers.web.entrypoints: "web"
      traefik.http.routers.web.middlewares: "httpsredirect@file"
      traefik.http.routers.web-ssl.rule: "Host(`{{ current_item.web.hostname  }}`)"
      traefik.http.routers.web-ssl.entrypoints: "websecure"
      traefik.http.routers.web-ssl.middlewares: "hsts@file,httpsredirect@file"
      traefik.http.routers.web-ssl.tls.certresolver: "letsencrypt"
      traefik.http.routers.web-ssl.tls.options: "intermediate@file"
      traefik.http.services.web-ssl.loadbalancer.server.port: "80"
    networks_cli_compatible: yes
    networks:
      - name: "{{ current_item.network }}"
