---
- name: "Define current scope values"
  set_fact: 
    current_item: "{{ hostvars[inventory_hostname].features[fitem] }}"

- name: "Add dns record for samba server name"
  nsupdate:
    key_name: "tsig-{{ nsupdate.zone }}"
    key_algorithm: "{{ nsupdate.tsig.algorithm | default('hmac-sha256') }}"
    key_secret: "{{ nsupdate.tsig.secret }}"
    server: "{{ nsupdate.server }}"
    zone: "{{ nsupdate.zone }}"
    type: "AAAA"
    record: "{{ current_item.samba.hostname }}."
    value: "{{ current_item.samba.ipv6 }}"
  when:
    - nsupdate.zone is defined
    - nsupdate.tsig is defined
    - nsupdate.server is defined
    - current_item.samba.hostname is defined
    - current_item.samba.ipv6 is defined

- name: "Create Samba share folder"
  file:
    path: "/opt/asset/{{ current_item.name | default(fitem) | lower }}/samba/share/"
    state: directory
    recurse: yes

- name: "Create Samba share configuration"
  template:
    src: share/smb.conf.j2
    dest: "/opt/asset/{{ current_item.name | default(fitem) | lower }}/samba/share/smb.conf"
    owner: root
    group: root
    mode: '0644'

- name: "Create Samba share container"
  docker_container:
    name: "{{ current_item.name | default(fitem) | lower }}.share"
    state: present
    restart_policy: unless-stopped
    image: "docker-samba/share"
    volumes:
      - "/opt/asset/{{ current_item.name | default(fitem) | lower }}/samba/share/:/app/samba/"
      - "{{ current_item.samba.volume }}:/app/volume/"
    env:
      TZ: "{{ timezone }}"
    networks_cli_compatible: yes
    networks:
      - name: "{{ current_item.network }}"
        ipv6_address: "{{ current_item.samba.ipv6 }}"

- name: "Start Samba share container"
  docker_container:
    name: "{{ current_item.name | default(fitem) | lower }}.share"
    state: started

- name: "Firewall Samba share inbound"
  ufw:
    rule: allow
    route: yes
    src: "::/0"
    dest: "{{ current_item.samba.ipv6 }}"
    proto: "tcp"
    port: "{{ item }}"
  loop: 
    - "445"

- name: "Create users"
  include: samba-share-user.yml
  loop: "{{ current_item.samba.users.keys() | list }}"
  loop_control:
    loop_var: "username"
  when: current_item.samba.users is defined

- name: "Set user/group on volume folder"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.share chown root:share /app/volume"
  failed_when: no
  changed_when: no

- name: "Set user/group on volume folder"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.share chmod 775 /app/volume"
  failed_when: no
  changed_when: no

- name: "Create share folder"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.share mkdir -p /app/volume/share"
  failed_when: no
  changed_when: no

- name: "Set user/group on share folder"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.share chown root:share /app/volume/share"
  failed_when: no
  changed_when: no

- name: "Set user/group on share folder"
  shell: "docker exec {{ current_item.name | default(fitem) | lower }}.share chmod 775 /app/volume/share"
  failed_when: no
  changed_when: no

- name: "Restart Samba share container"
  docker_container:
    name: "{{ current_item.name | default(fitem) | lower }}.share"
    state: started
    restart: yes