---
## Setup Hostname
- name: "Hostname"
  hostname: 
    name: "{{ inventory_hostname }}"

- name: "Generate hosts file"
  template:
    src: hosts.j2
    dest: "/etc/hosts"

## Setup Timezone
- name: "Configure timezone"
  timezone:
    hwclock: UTC
    name: "{{ timezone }}"
  when: timezone is defined


## Specific distribution
- name: "{{ ansible_distribution }} Home System Setup"
  include: "{{ ansible_distribution | lower }}/00-main.yml"
  when: system is defined
