---
- name: Install NUT
  apt:
    name: "nut"
    state: present

- name: Generate NUT UPS files
  template:
    src: nut/{{ item }}.j2
    dest: "/etc/nut/{{ item }}"
    owner: root
    group: nut
    mode: '0640'
  loop: 
    - "nut.conf"
    - "ups.conf"
    - "upsd.users"
    - "upsmon.conf"

- name: Restart NUT Server
  service:
    name: nut-server
    state: restarted

- name: Restart NUT Client
  service:
    name: nut-monitor
    state: restarted
