---
- name: "Create Zigbee2MQTT data volume"
  docker_volume:
    name: "hass_broker_data"
    state: present

- name: "Create Zigbee2MQTT folder"
  file:
    path: "/opt/home/hass/zigbee/"
    state: directory
    recurse: yes

- name: "Create Zigbee2MQTT container"
  docker_container:
    name: "hass.zigbee"
    state: present
    restart_policy: unless-stopped
    image: "koenkk/zigbee2mqtt:{{ zigbee2mqtt_version }}"
    volumes:
      - "hass_broker_data:/app/data"
      - "/opt/home/hass/zigbee/configuration.yaml:/app/data/configuration.yaml"
    devices:
      - "{{ features.hass.adapter.zigbee.device }}"
    env:
      TZ: "{{ timezone }}"
    networks_cli_compatible: yes
    networks:
      - name: "{{ features.hass.network }}"
        ipv6_address: "{{ features.hass.adapter.zigbee.ipv6  }}"
    links:
      - "hass.broker"

- name: "Start Zigbee2MQTT container"
  docker_container:
    name: "hass.zigbee"
    state: started

- name: "Zigbee2MQTTAssistant"
  include: "zigbee-zigbee2mqttassistant.yml"
  when: 
    - features.hass.adapter.zigbee.admin_ipv6
    - features.hass.adapter.zigbee.admin_hostname