---
- name: "Plex setup"
  include: "plex-setup.yml"
  when: 
    - features.multimedia is defined
    - features.multimedia.plex is defined

- name: "Jellyfin setup"
  include: "jellyfin-setup.yml"
  when: 
    - features.multimedia is defined
    - features.multimedia.jellyfin is defined

- name: "PyLoad setup"
  include: "pyload-setup.yml"
  when: 
    - features.multimedia is defined
    - features.multimedia.pyload is defined

- name: "Squid setup"
  include: "squid-setup.yml"
  when: 
    - features.multimedia is defined
    - features.multimedia.squid is defined

- name: "JDownloader setup"
  include: "jdownloader-setup.yml"
  when: 
    - features.multimedia is defined
    - features.multimedia.jdownloader is defined